name: rj_thesis_project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - plotly
  - phidl
  - jupyterlab
  - ipykernel
  - pytest
  - pyyaml
  - h5py
  - tqdm
  - pip:
      - nextnanopy
